# -*- coding: utf-8 -*-
"""c131.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYAuH9v0hzxORplmxZ13nFd1QiZ3sJB-
"""

import pandas as pd

from google.colab import files
data_to_load=files.upload()

df=pd.read_csv('total_stars.csv')
df.head()

df.columns
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.head()

df['Radius']=df['Radius'].apply(lambda x: x.replace('$','').replace(',','')).astype('float')

radius=df['Radius'].to_list()
mass=df['Mass'].to_list()
gravity=[]

def convert_to_si(radius,mass):
  for i in range(0,len(radius)-1):
    radius[i]=radius[i]*6.957e+8
    mass[i]=mass[i]*1.989e+30

convert_to_si(radius,mass)

def gravity_calculation(radius,mass):
  G=6.674e-11
  for index in range(0, len(mass)):
    g=(mass[index]*G)/((radius[index])**2)
    gravity.append(g)

gravity_calculation(radius,mass)

df["Gravity"] = gravity
df

df.to_csv("star_with_gravity.csv")
df.dtypes